# Generated by Django 4.2.7 on 2023-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='Likes', to='app.profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='tagquestion',
            field=models.ManyToManyField(related_name='TagQuestion', to='app.tag'),
        ),
    ]
